src/main/java/com/sparta/actionboss/domain/post/controller/HelloController.java
=> #8 / feat: add test HelloController

scripts/start.sh
=> #12 / docs: update start.sh

src/main/java/com/sparta/actionboss/domain/auth/controller/UserController.java, src/main/java/com/sparta/actionboss/domain/auth/dto/NicknameCheckRequestDto.java, src/main/java/com/sparta/actionboss/domain/auth/service/UserService.java
add nickname duplication check function
=> #15 / feat : add nickname duplication check function

src/main/java/com/sparta/actionboss/domain/post/service/S3Service.java
Modify folder path because it runs locally but does not run on the server
=> #21 / fix: Modify folder path

src/main/java/com/sparta/actionboss/global/config/WebMvcConfig.java, src/main/java/com/sparta/actionboss/global/config/WebSecurityConfig.java
- Add .gitkeep to preserve empty images directory
=> #23 / docx: Add .gitkeep to preserve empty images directory

src/main/java/com/sparta/actionboss/domain/post/service/S3Service.java
fix: modify system path (S3Service) : server error
=> #27 / merge: modify S3Service

src/main/java/com/sparta/actionboss/domain/post/service/S3Service.java
- modify system path (S3Service) : server error (2)
=> #29 / merge: modify system path (S3Service) : server error (2)

src/main/java/com/sparta/actionboss/domain/post/controller/PostController.java, src/main/java/com/sparta/actionboss/domain/post/dto/CreatePostResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/dto/PostResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/dto/UpdatePostResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/entity/Post.java, src/main/java/com/sparta/actionboss/domain/post/service/PostService.java, src/main/java/com/sparta/actionboss/domain/post/service/S3Service.java
- createPostResponseDto
- updatePostResponseDto
- deletePostResponseDto
- S3Service: folder name (UUID.randomUUID) -> (postId)
- Post Entity: image urls -> image names
=> #33 / fix: modify responseDto, S3 folder name, images url to images name

src/main/java/com/sparta/actionboss/domain/post/dto/PostModalResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/service/PostGetService.java
- fix: ImageUrls -> ImageNames
=> #36 / merge: ImageUrls -> ImageNames

src/main/java/com/sparta/actionboss/domain/post/service/S3Service.java
- When the file name has and does not have a "-" 
- fix index error (S3Service)
=> #38 / fix: file name has "-", doesn't have "-"

src/main/java/com/sparta/actionboss/domain/post/controller/PostGetController.java, src/main/java/com/sparta/actionboss/domain/post/dto/MapListResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/dto/PostListAndTotalPageResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/dto/PostModalResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/repository/PostRepository.java, src/main/java/com/sparta/actionboss/domain/post/service/PostGetService.java
- add getMapList
- add presentPage
- fix UrlPrefix
=> #40 / merge: add getMapList, add presentPage, fix UrlPrefix

src/main/java/com/sparta/actionboss/domain/done/controller/PostDoneController.java, src/main/java/com/sparta/actionboss/domain/done/dto/CancelPostDoneResponseDto.java, src/main/java/com/sparta/actionboss/domain/done/dto/PostDoneResponseDto.java, src/main/java/com/sparta/actionboss/domain/done/entity/PostDone.java, src/main/java/com/sparta/actionboss/domain/done/repository/PostDoneRepository.java, src/main/java/com/sparta/actionboss/domain/done/service/PostDoneService.java, src/main/java/com/sparta/actionboss/domain/post/controller/PostController.java, src/main/java/com/sparta/actionboss/domain/post/dto/PostResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/entity/Post.java, src/main/java/com/sparta/actionboss/domain/post/service/PostService.java
=> #44 / merge: add PostDone

src/main/java/com/sparta/actionboss/domain/done/controller/PostDoneController.java, src/main/java/com/sparta/actionboss/domain/done/service/PostDoneService.java, src/main/java/com/sparta/actionboss/domain/post/controller/AgreeController.java, src/main/java/com/sparta/actionboss/domain/post/entity/Agree.java, src/main/java/com/sparta/actionboss/domain/post/repository/AgreeRepository.java, src/main/java/com/sparta/actionboss/domain/post/service/AgreeService.java, src/main/java/com/sparta/actionboss/global/exception/AgreeException.java, src/main/java/com/sparta/actionboss/global/exception/errorcode/ClientErrorCode.java, src/main/java/com/sparta/actionboss/global/response/SuccessMessage.java
=> #48 / feat : add agree function

src/main/java/com/sparta/actionboss/domain/post/controller/PostDoneController.java, src/main/java/com/sparta/actionboss/domain/post/dto/PostResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/entity/Post.java, src/main/java/com/sparta/actionboss/domain/post/entity/PostDone.java, src/main/java/com/sparta/actionboss/domain/post/repository/PostDoneRepository.java, src/main/java/com/sparta/actionboss/domain/post/service/PostDoneService.java, src/main/java/com/sparta/actionboss/domain/post/service/PostService.java
- feat: add response postId(create post)
=> #55 / merge: add response postId(create post)

src/main/java/com/sparta/actionboss/domain/post/controller/PostController.java, src/main/java/com/sparta/actionboss/domain/post/controller/PostGetController.java, src/main/java/com/sparta/actionboss/domain/post/service/PostGetService.java, src/main/java/com/sparta/actionboss/global/exception/errorcode/ClientErrorCode.java
- add CommonResponse (MainPage)
- add Exception (MainPage)
=> #60 / merge: add CommonResponse, Exception (MainPage)

src/main/java/com/sparta/actionboss/global/config/WebMvcConfig.java
modify frontend's domain address
=> #64 / fix : modify frontend domain address

src/main/java/com/sparta/actionboss/global/config/WebMvcConfig.java
add another frontend's address
=> #66 / fix : add another frontend address

src/main/java/com/sparta/actionboss/global/config/WebMvcConfig.java
=> #68 / fix : remove unused code

src/main/java/com/sparta/actionboss/global/config/WebMvcConfig.java
add new frontend's domain address
=> #70 / fix : add new frontend domain address

src/main/java/com/sparta/actionboss/domain/post/controller/PostGetController.java, src/main/java/com/sparta/actionboss/domain/post/entity/Image.java, src/main/java/com/sparta/actionboss/domain/post/entity/Post.java, src/main/java/com/sparta/actionboss/domain/post/repository/ImageRepository.java, src/main/java/com/sparta/actionboss/domain/post/service/PostGetService.java, src/main/java/com/sparta/actionboss/domain/post/service/PostService.java, src/main/java/com/sparta/actionboss/domain/post/service/S3Service.java, src/main/java/com/sparta/actionboss/global/advice/CustomExceptionHandler.java, src/main/java/com/sparta/actionboss/global/exception/ImageException.java, src/main/java/com/sparta/actionboss/global/exception/S3Exception.java, src/main/java/com/sparta/actionboss/global/exception/errorcode/ClientErrorCode.java
- modify images folder name(S3)
- S3 exception
=> #72 / merge: modify images folder name, S3 exception

src/main/java/com/sparta/actionboss/domain/post/entity/Post.java
- modify the number of characters (title, content)
=> #74 / merge: modify the number of characters (title, content)

src/main/java/com/sparta/actionboss/domain/post/dto/PostResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/service/PostService.java
- add postDone (PostResponseDto)
=> #76 / merge : add postDone (ResponseDto)

src/main/java/com/sparta/actionboss/domain/auth/entity/User.java, src/main/java/com/sparta/actionboss/domain/post/controller/CommentController.java, src/main/java/com/sparta/actionboss/domain/post/dto/CommentRequestDto.java, src/main/java/com/sparta/actionboss/domain/post/dto/CommentResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/dto/PostResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/entity/Comment.java, src/main/java/com/sparta/actionboss/domain/post/entity/Post.java, src/main/java/com/sparta/actionboss/domain/post/repository/CommentRepository.java, src/main/java/com/sparta/actionboss/domain/post/service/CommentService.java, src/main/java/com/sparta/actionboss/domain/post/service/PostService.java, src/main/java/com/sparta/actionboss/global/advice/CustomExceptionHandler.java, src/main/java/com/sparta/actionboss/global/config/WebMvcConfig.java, src/main/java/com/sparta/actionboss/global/exception/CommentException.java, src/main/java/com/sparta/actionboss/global/exception/errorcode/ClientErrorCode.java, src/main/java/com/sparta/actionboss/global/response/SuccessMessage.java
- add createdTime (CommentResponseDto)
- add createdDay (CommentResponseDto)
- fix createdAt (PostResponseDto) 'YYYY-MM-DD' -> 'YYYY.MM.DD'
=> #80 / merge: add time, day

src/main/java/com/sparta/actionboss/global/filter/JwtAuthorizationFilter.java, src/main/java/com/sparta/actionboss/global/security/JwtUtil.java
=> #82 merge: CORS error TRY

src/main/java/com/sparta/actionboss/global/filter/JwtAuthorizationFilter.java
#88 / edit: readme
- fix: CORS error TRY
=> #84 / merge: CORS error TRY

src/main/java/com/sparta/actionboss/domain/auth/service/UserService.java, src/main/java/com/sparta/actionboss/global/filter/JwtAuthorizationFilter.java, src/main/java/com/sparta/actionboss/global/security/JwtUtil.java
=> #86 / merge: CORS error TRY

src/main/java/com/sparta/actionboss/global/config/WebMvcConfig.java, src/main/java/com/sparta/actionboss/global/filter/JwtAuthorizationFilter.java
=> #90 / fix : modify exposed header

src/main/java/com/sparta/actionboss/domain/post/dto/CommentResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/dto/PostResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/service/PostService.java
- CommentResponseDto add commentOwner
=> #94 / merge: CommentResponseDto add commentOwner

src/main/java/com/sparta/actionboss/domain/post/service/PostService.java
- add owner (accidental omission)
=> #96 / merge: postResponseDto fix owner

src/main/java/com/sparta/actionboss/domain/auth/controller/UserController.java, src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java
modify HttpStatus code,
delete double quotation marks from client id
=> #100 / fix : modify Httpstatus code

src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java
modify kakaotalk login redirect uri
=> fix : modify kakaotalk login redirect uri

src/main/java/com/sparta/actionboss/domain/post/service/PostService.java, src/main/java/com/sparta/actionboss/domain/post/service/S3Service.java
- S3 upload using ObjectMetadata
=> #106 / merge: S3 upload using ObjectMetadata

src/main/java/com/sparta/actionboss/domain/auth/entity/User.java, src/main/java/com/sparta/actionboss/domain/auth/repository/UserRepository.java, src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java, src/main/java/com/sparta/actionboss/domain/auth/service/UserService.java, src/main/java/com/sparta/actionboss/domain/mypage/controller/MyPageController.java, src/main/java/com/sparta/actionboss/domain/mypage/dto/UpdateEmailRequestDto.java, src/main/java/com/sparta/actionboss/domain/mypage/service/MyPageService.java, src/main/java/com/sparta/actionboss/global/exception/errorcode/ClientErrorCode.java, src/main/java/com/sparta/actionboss/global/response/SuccessMessage.java
=> #112 / feat : add update email

src/main/java/com/sparta/actionboss/domain/post/controller/DoneController.java, src/main/java/com/sparta/actionboss/domain/post/entity/Done.java, src/main/java/com/sparta/actionboss/domain/post/entity/Post.java, src/main/java/com/sparta/actionboss/domain/post/repository/DoneRepository.java, src/main/java/com/sparta/actionboss/domain/post/service/DoneService.java, src/main/java/com/sparta/actionboss/domain/post/service/PostService.java
- rename: modify PostDone to Done
=> #114 / merge: modify PostDone to Done

src/main/java/com/sparta/actionboss/global/advice/CustomExceptionHandler.java
- Modify CustomExceptionHandler.java > SearchException
=> fix : search CORS error

src/main/java/com/sparta/actionboss/global/advice/CustomExceptionHandler.java
fix: modify ExceptionHandler > searchException
=> fix: modify CORS error

src/main/java/com/sparta/actionboss/domain/notification/controller/NotificationController.java, src/main/java/com/sparta/actionboss/domain/notification/service/NotificationService.java, src/main/java/com/sparta/actionboss/domain/post/entity/Done.java, src/main/java/com/sparta/actionboss/domain/post/service/AgreeService.java, src/main/java/com/sparta/actionboss/domain/post/service/CommentService.java, src/main/java/com/sparta/actionboss/domain/post/service/DoneService.java, src/main/java/com/sparta/actionboss/global/response/SuccessMessage.java
- fix done SQL error 
: Done Entity id -> Done Entity doneId
- modify calling notificationService method
: commentService, agreeService, doneService
=> #132 / merge: done SQL error, modify calling notificationService method

src/main/java/com/sparta/actionboss/domain/notification/controller/NotificationController.java, src/main/java/com/sparta/actionboss/domain/notification/service/NotificationService.java, src/main/java/com/sparta/actionboss/domain/post/service/CommentService.java
- fix commentService: show only alerts to others
- modify log message (SSE subscribe, unsubscribe)
=> #134 / merge: CommentService (Show only alerts to others), modify log msg

src/main/java/com/sparta/actionboss/domain/auth/controller/UserController.java, src/main/java/com/sparta/actionboss/domain/auth/dto/ReissueTokenResponseDto.java, src/main/java/com/sparta/actionboss/domain/auth/entity/RefreshToken.java, src/main/java/com/sparta/actionboss/domain/auth/entity/User.java, src/main/java/com/sparta/actionboss/domain/auth/repository/RefreshTokenRepository.java, src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java, src/main/java/com/sparta/actionboss/domain/auth/service/UserService.java, src/main/java/com/sparta/actionboss/global/advice/CustomExceptionHandler.java, src/main/java/com/sparta/actionboss/global/config/WebMvcConfig.java, src/main/java/com/sparta/actionboss/global/exception/MyPageException.java, src/main/java/com/sparta/actionboss/global/exception/errorcode/ClientErrorCode.java, src/main/java/com/sparta/actionboss/global/filter/JwtAuthorizationFilter.java, src/main/java/com/sparta/actionboss/global/response/SuccessMessage.java, src/main/java/com/sparta/actionboss/global/security/UserDetailsServiceImpl.java, src/main/java/com/sparta/actionboss/global/util/JwtUtil.java
=> #136 / feat : add refresh token

src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java, src/main/java/com/sparta/actionboss/domain/mypage/controller/MyPageController.java, src/main/java/com/sparta/actionboss/domain/mypage/dto/MyPageInfoResponseDto.java, src/main/java/com/sparta/actionboss/domain/mypage/service/MyPageService.java, src/main/java/com/sparta/actionboss/global/exception/errorcode/ClientErrorCode.java
=> #137 : feat : add update password

src/main/java/com/sparta/actionboss/domain/notification/entity/Notification.java, src/main/java/com/sparta/actionboss/domain/notification/service/NotificationService.java
- fix NullPointException error (postDone: actor_user_id)
=> #140 / merge: postDone NullPointException error (SSE)

src/main/java/com/sparta/actionboss/domain/post/controller/PostGetController.java, src/main/java/com/sparta/actionboss/domain/post/dto/PostModalResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/repository/PostRepository.java, src/main/java/com/sparta/actionboss/domain/post/service/PostGetService.java
- refactor: Optimize getPostList and getMapList using JPQL
=> #144 / merge: Optimize getPostList and getMapList using JPQL

src/main/java/com/sparta/actionboss/global/config/WebSecurityConfig.java
=> #148 / fix : CORS error 2

src/main/java/com/sparta/actionboss/global/filter/JwtAuthorizationFilter.java
JwtAuthorizationfilter refactoring
=> #150 : refactor : filter refactoring

src/main/java/com/sparta/actionboss/domain/post/service/PostService.java
- fix: PostService modify getUser Information (nickname -> userId)
=> #152 / merge: modify PostService

src/main/java/com/sparta/actionboss/domain/auth/entity/User.java, src/main/java/com/sparta/actionboss/domain/notification/repository/NotificationRepository.java, src/main/java/com/sparta/actionboss/domain/post/dto/CommentResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/entity/Post.java
- modify CommentResponseDto
- modify  user withdrawal
=> #155 / fix: modify CommentResponseDto, user withdrawal

src/main/java/com/sparta/actionboss/domain/auth/entity/User.java, src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java, src/main/java/com/sparta/actionboss/domain/auth/service/UserService.java, src/main/java/com/sparta/actionboss/domain/mypage/service/MyPageService.java, src/main/java/com/sparta/actionboss/global/util/JwtUtil.java
modify jwt (nickname to userId)
=> #154 / fix : modify jwt

src/main/java/com/sparta/actionboss/domain/mypage/service/MyPageService.java
=> #158 / fix : mypage getUserInfo

src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java, src/main/java/com/sparta/actionboss/domain/auth/service/UserService.java, src/main/java/com/sparta/actionboss/domain/mypage/controller/MyPageController.java, src/main/java/com/sparta/actionboss/domain/mypage/dto/UpdateNicknameResponseDto.java, src/main/java/com/sparta/actionboss/domain/mypage/service/MyPageService.java, src/main/java/com/sparta/actionboss/global/util/JwtUtil.java
modify jwt(userId to nickname), 
modify updateNickname
=> #160 / fix : modify jwt, updateNickname

src/main/java/com/sparta/actionboss/domain/mypage/controller/MyPageController.java, src/main/java/com/sparta/actionboss/domain/mypage/service/MyPageService.java, src/main/java/com/sparta/actionboss/global/util/JwtUtil.java
=> #162 / fix : updateNickname

src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java, src/main/java/com/sparta/actionboss/domain/mypage/service/MyPageService.java
modify kakao login redirect_uri
=> #164 / fix : modify kakao login redirect_uri

src/main/java/com/sparta/actionboss/domain/mypage/controller/MyPagePostController.java, src/main/java/com/sparta/actionboss/domain/mypage/dto/MyPagePostsResponseDto.java, src/main/java/com/sparta/actionboss/domain/mypage/dto/PagingResponseDto.java, src/main/java/com/sparta/actionboss/domain/mypage/service/MyPagePostService.java, src/main/java/com/sparta/actionboss/domain/post/repository/AgreeRepository.java, src/main/java/com/sparta/actionboss/domain/post/repository/CommentRepository.java, src/main/java/com/sparta/actionboss/domain/post/repository/PostRepository.java, src/main/java/com/sparta/actionboss/domain/post/service/S3Service.java
- add mypage
- get myposts
- get my comments posts
- get my agree posts
=> #166 / merge: add mypage

src/main/java/com/sparta/actionboss/domain/mypage/dto/MyPagePostsResponseDto.java, src/main/java/com/sparta/actionboss/global/config/WebSecurityConfig.java
- modify MyPagePostsResponseDto
: createdAt -> createdDay, createdTime
- modify WebSecurityConfig
=> #169 / merge: modify MyPagePostsResponseDto, WebSecurityConfig

src/main/java/com/sparta/actionboss/global/config/WebSecurityConfig.java, src/main/java/com/sparta/actionboss/global/util/JwtUtil.java
=> #168 / fix : modify jwt time

src/main/java/com/sparta/actionboss/domain/post/dto/CommentResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/dto/PostResponseDto.java, src/main/java/com/sparta/actionboss/domain/post/service/PostService.java
- fix modify commentResponse > commentOwner 
: add authority user role ADMIN
=> merge: modify commentOwner, add owner ADMIN

src/main/java/com/sparta/actionboss/domain/mypage/dto/MyPagePostsResponseDto.java, src/main/java/com/sparta/actionboss/domain/mypage/service/MyPagePostService.java
- modify createdDay (Post -> Comment, Agree)
- modify createdTime (Post -> Comment, Agree)
=> #174 / fix: modify createdDay, createdTime

src/main/java/com/sparta/actionboss/domain/mypage/dto/MyPagePostsResponseDto.java
- fix: modify createdDay, createdTime (YYYY -> YY)
=> #176 / merge: modify createdDay, createdTime (YYYY -> YY)

src/main/java/com/sparta/actionboss/domain/auth/controller/UserController.java, src/main/java/com/sparta/actionboss/domain/auth/entity/RefreshToken.java, src/main/java/com/sparta/actionboss/domain/auth/repository/RefreshTokenRepository.java, src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java, src/main/java/com/sparta/actionboss/domain/auth/service/UserService.java, src/main/java/com/sparta/actionboss/domain/mypage/service/MyPageService.java, src/main/java/com/sparta/actionboss/global/config/WebSecurityConfig.java
add the delete logic of the previous refresh token
=> #178 / fix : add the delete logic of the previous refresh token

src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java, src/main/java/com/sparta/actionboss/domain/auth/service/UserService.java
=> #180 / fix : modify login return type

src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java
=> fix : modify kakaoService

src/main/java/com/sparta/actionboss/domain/auth/controller/UserController.java, src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java
=> #184 / refactor : modify return type

src/main/java/com/sparta/actionboss/domain/auth/service/KakaoService.java
add transactional at kakaologin
=> #186 / fix : add transactional at kakaologin
